# Generated by Django 4.2.16 on 2024-11-13 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0005_delete_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarefa', models.CharField(max_length=100, verbose_name='Tarefa')),
                ('prioridade', models.IntegerField(blank=True, verbose_name='Prioridade')),
                ('descricao', models.TextField(blank=True, max_length=500)),
            ],
            options={
                'verbose_name': 'Tarefa',
                'verbose_name_plural': 'Tarefas',
                'ordering': ['tarefa'],
            },
        ),
    ]
